version: "3.7"

services:
  app:
    build: .
    environment:
      REDIS_URL: redis:6379
      PORT: 8080
      ACCESS_SECRET: thisisanawesomeaccesssecret
      REFRESH_SECRET: thisisanawesomerefreshsecret
    ports:
      - 8080:8080
  redis:
    image: redis:5.0.7
